version: '3.9'

services:

    laravel:
        build:
            context: .
            target: php-dev
        volumes:
            - '.:/var/www/html'

    nginx:
        build:
            context: .
            target: nginx-dev
        ports:
            - '${FORWARD_APP_PORT:-80}:80'
        volumes:
            - './public/:/usr/share/nginx/html/'

    node:
        build:
            context: .
            target: node-dev
        volumes:
            - '.:/home/node/app'

    mysql:
        image: 'mysql:8.0'
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        volumes:
            - 'mysql:/var/lib/mysql'

    redis:
        image: 'redis:alpine'
        ports:
            - '${FORWARD_REDIS_PORT:-6379}:6379'
        volumes:
            - 'redis:/data'

    meilisearch:
        image: 'getmeili/meilisearch:latest'
        ports:
            - '${FORWARD_MEILISEARCH_PORT:-7700}:7700'
        volumes:
            - 'meilisearch:/data.ms'

    mailhog:
        image: 'mailhog/mailhog:latest'
        ports:
            - '${FORWARD_MAILHOG_PORT:-1025}:1025'
            - '${FORWARD_MAILHOG_DASHBOARD_PORT:-8025}:8025'

    selenium:
       image: 'selenium/standalone-chrome'
       volumes:
            - '/dev/shm:/dev/shm'

volumes:
    mysql:
        driver: local
    redis:
        driver: local
    meilisearch:
        driver: local
