apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: laravel
  name: laravel
spec:
  replicas: 1
  selector:
    matchLabels:
      app: laravel
  template:
    metadata:
      labels:
        app: laravel
    spec:
      containers:
      - image: kartoch/laravel-prod:latest
        name: laravel-prod
