apiVersion: v1
kind: Service
metadata:
  labels:
    app: laravel-service
  name: laravel-service
spec:
  ports:
  - name: php-fpm
    port: 9000
    protocol: TCP
    targetPort: 9000
  selector:
    app: laravel
  type: ClusterIP
